# Generated by Django 3.1 on 2020-05-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunaute', '0002_auto_20200511_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatureDemande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Command',
        ),
    ]
