# Generated by Django 3.1 on 2020-05-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunaute', '0006_commande_panier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='user',
        ),
        migrations.AddField(
            model_name='panier',
            name='idcommande',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='comunaute.commande'),
            preserve_default=False,
        ),
    ]
