# Generated by Django 3.1 on 2020-05-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunaute', '0008_commande_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
