# Generated by Django 3.1 on 2020-05-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunaute', '0009_auto_20200521_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.CharField(max_length=60),
        ),
    ]
