# Generated by Django 3.1 on 2020-05-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunaute', '0010_auto_20200521_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='enattente',
            field=models.BooleanField(default=True),
        ),
    ]
