# Generated by Django 3.1 on 2020-05-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunaute', '0011_commande_enattente'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adresseip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
